# Generated by Django 5.0.7 on 2024-07-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='university',
        ),
    ]
