# Generated by Django 5.0.7 on 2024-07-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
