# Generated by Django 5.0.7 on 2024-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_user_alter_board_ob_alter_board_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
