# Generated by Django 5.0.7 on 2024-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_remove_board_date_remove_board_ob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="blogcnt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="maindoctorcnt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="visitcnt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
